---
- name: Build Docker image from Dockerfile
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    path: "Users/HomeMac/vagrant/projects/vagrant-automation/provisioner/provisioning/vagrant1/{{ item.directory }}"

    state: build


  with_items:

   - { name: nginx, tag: "v1", directory: nginx }

- name: Run a nginx  container.

  docker_container:

    image: nginx:v1

    name: nginx

    state: started






















